version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin
      - MARIADB_DATABASE=solar-panel
    volumes:
      - ./data:/bitnami/mariadb

  laravel:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_DATABASE=solar-panel
    volumes:
      - './back-end:/app'
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - '8001:80'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=admin
      - PMA_PASSWORD=
      - PMA_ARBITRARY=1

    depends_on:
      - mariadb

